config/routes.rb
Rails.application.routes.draw do
  root 'pages#home', as: :root
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  get '/' => 'pages#home', as: :home
  get '/faq' => 'pages#faq', as: :faq
  get '/help' => 'pages#help', as: :help
  get 'view_drugs' => 'pages#viewdrugs', as: :viewdrugs
  get 'view_ingredients' => 'pages#viewingredients', as: :viewingredients
  post '/import' => 'drugs#importcsv', as: :importcsv

  get 'drugs/query', defaults: { format: 'json' }

  resources :relationships
  resources :ingredients
  resources :drugs do
    put :make_relationship, :action => :make_relationship
  end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

	validates :name, presence: true, uniqueness: { case_sensitive: false }
	validates :allowed, presence: true
	
	has_many :relationships, :foreign_key => :ingredient_id, :dependent => :destroy
	has_many :drugs, :through => :relationships
	
	searchable do
		text :name, boost: 5
		text :description
	end
	
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :require_login
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
  layout 'main'
  # GET /ingredients
  # GET /ingredients.json

  def index
    require_admin
    @search = Ingredient.search do
      fulltext params[:search]
    end
    @ingredients = @search.results
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    require_admin
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
    require_admin
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    require_admin
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    require_admin
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    require_admin
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def query
    search = Ingredient.search do
      fulltext params[:q]
    end
 
    respond_to do |format|
      format.json do
        results = search.results.map do |drug|
          { name: ingredient.name, link: "https://sleepy-tor-6329.herokuapp.com/ingredient/#{ingredient.id}" }
        end
        render json: results
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :description, :allowed)
    end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper

def ingredient_partial
	
	if @ingredient.allowed == "no"
		render 'ingredient_red'

	elsif @ingredient.allowed == "warning"
		render 'ingredient_yellow'
	
	elsif @ingredient.allowed == "yes"		
		render 'ingredient_green'

	end

end
	

end

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :allowed %><br>
    <%= f.text_field :allowed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredient_green.html.erb
<div class="red-message">
<h3 class="code-green-header"><%= @ingredient.name %></h3>
<h4>Leki zawierające substancję są dozwolone do użytku.</h4>
</div>

app/views/ingredients/_ingredient_red.html.erb
<div class="red-message">
<h3 class="code-red-header"><%= @ingredient.name %></h3>
<h4>Leki zawierające substancję są niedozwolone.</h4>
</div>

app/views/ingredients/_ingredient_yellow.html.erb
<div class="red-message">
<h3 class="code-yellow-header"><%= @ingredient.name %></h3>
<h4>Substancja może być niedozwolona.</h4>
</div>

app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Allowed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.description %></td>
        <td><%= ingredient.allowed %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<div class="results-wrap results-wrap-show">
      <div class="drug-wrap drug-wrap-show">
        <div>
        	<%= ingredient_partial %>
          
          <p><%= @ingredient.description %></p>
        </div>
        <p><b>Substancja występuje w następujących lekach:</b></p>
        <div class="ingredients-cloud">
			<% Relationship.where(ingredient_id: @ingredient.id).each do |relationship| %>
			 <span class="active_ingredient code-blue"><%= link_to "#{Drug.find_by(id: relationship.drug_id ).name}", Drug.find_by(id: relationship.drug_id )  %> </span>
			<% end %>
		</div> 
       </div>



	</div>
</div>