config/routes.rb
Rails.application.routes.draw do
  root 'pages#home', as: :root
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  get '/' => 'pages#home', as: :home
  get '/faq' => 'pages#faq', as: :faq
  get '/help' => 'pages#help', as: :help
  get 'view_drugs' => 'pages#viewdrugs', as: :viewdrugs
  get 'view_ingredients' => 'pages#viewingredients', as: :viewingredients
  post '/import' => 'drugs#importcsv', as: :importcsv

  get 'drugs/query', defaults: { format: 'json' }

  resources :relationships
  resources :ingredients
  resources :drugs do
    put :make_relationship, :action => :make_relationship
  end

end

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<div class="topbar-wrap">

<div id="user-nav" style="position: relative">
<% if user_signed_in? %>
Logged in as <strong><%= current_user.email %></strong>.
<div><span id="edit-profile"><%= link_to 'Edit profile', edit_user_registration_path %></span>
<span id="logout"><%= link_to 'Logout', destroy_user_session_path, method: :delete %></span></div>
<% else %>
<%= link_to 'Sign up', new_user_registration_path %>
<%= link_to 'Login', new_user_session_path %>
<% end %>
</div>

<nav class="nav">
	<ul>
		<%= link_to "<li>FAQ</li>".html_safe, faq_path %>
      <%= link_to "<li>Pomoc</li>".html_safe, help_path %>
	</ul>
</nav>
</div>

<div class="search-wrap-home inner-addon right-addon">
	<h1>Search Meds</h1>
	<%= form_tag drugs_path, :method => :get do %>
	<%= text_field_tag :search, params[:search], :class => "typeahead form-control" %>
	<%= button_tag(type: "submit", class: "btn btn-default search-button-home") do %>
    <i class="glyphicon glyphicon-search"></i>
	<% end %>
	<% end %>
</div>

<% if current_user.admin? %>

<div id="admin-link">
<%= link_to "<li>Admin panel</li>".html_safe, viewdrugs_path %>
</div>

<% end %>

app/views/pages/viewdrugs.html.erb
<div id="admin-viewdrugs-wrap">
<%= link_to '<div class="btn btn-default new-item">New Drug</div>'.html_safe, new_drug_path %>

<div style="float: right"><h4>Import CSV</h4>
<%= form_tag importcsv_path, multipart: true do |f| %>
	<%= file_field_tag :file %>
	<%= submit_tag "Import" %>
<% end %>
</div>

<%= form_tag viewdrugs_path, :method => 'get', :id => "viewdrugs_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  
<% end %>

<table>
<thead>
<tr>
<th>Name</th>
<th>Description</th>
<th>Ingredients</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @drugs.each do |drug| %>
<tr>
<td><%= drug.name %></td>
<td><%= drug.description %></td>
<td><%= Ingredient.where(id: Relationship.where(drug_id: drug.id).all.map(&:ingredient_id)).all.map(&:name).join(', ') %></td>
<td><span class="btn btn-default"><%= link_to 'Show', drug %></span></td>
<td><span class="btn btn-default"><%= link_to 'Edit', edit_drug_path(drug) %></span></td>
<td><span class="btn btn-default"><%= link_to 'Destroy', drug, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
</tr>
<% end %>
<%= will_paginate @drugs %>
</tbody>
</table>
</div>

app/views/pages/viewingredients.html.erb
<div id="admin-viewdrugs-wrap">
<%= link_to '<div class="btn btn-default new-item">New Ingredient</div>'.html_safe, new_ingredient_path %>

<%= form_tag viewingredients_path, :method => 'get', :id => "viewingredients_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  
<% end %>

<table>
<thead>
<tr>
<th>Name</th>
<th>Description</th>
<th>Appears in:</th>
<th colspan="3"></th>
</tr>
</thead>
<tbody>
<% @ingredients.each do |ingredient| %>
<tr>
<td><%= ingredient.name %></td>
<td><%= ingredient.description %></td>
<td><%= Ingredient.where(id: Relationship.where(ingredient_id: ingredient.id).all.map(&:drug_id)).all.map(&:name).join(', ') %></td>
<td><span class="btn btn-default"><%= link_to 'Show', ingredient %></span></td>
<td><span class="btn btn-default"><%= link_to 'Edit', edit_ingredient_path(ingredient) %></span></td>
<td><span class="btn btn-default"><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
</tr>
<% end %>
<%= will_paginate @ingredients %>
</tbody>
</table>

</div>